# Add 'CI/CD' label to any change within .github/workflows
CI/CD:
  - .github/workflows/*
  - .github/workflows/**/*

# Add 'security' label to any change to the security CI workflow
security:
  - .github/workflows/security.yml

# Add 'documentation' label to any changes to markdown files
documentation:
  - **/*.md
  - *.md
