name: Misc

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  actionlint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download actionlint
        uses: reviewdog/action-actionlint@v1.29.0
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.15.0
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true

  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.6.1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
